import type { TelegramWebApp } from './webapp';

/**
 * Dev-only emulator for window.Telegram.WebApp so the Mini App can be opened
 * and clicked through in a plain browser (outside real Telegram) during
 * development. Only wired up behind `import.meta.env.DEV` in main.tsx, so it
 * never ships in the production bundle.
 *
 * Backend calls that require a verified identity (register/booking/cancel)
 * still need a genuinely HMAC-signed initData string — pass one via
 * `?devInitData=...` generated by scripts/generate-test-init-data.mjs. This
 * stub never has access to the bot token; it only carries whatever string
 * you hand it.
 */
export function installDevTelegramStub() {
  if (typeof window === 'undefined' || window.Telegram) return;

  const initData = new URLSearchParams(window.location.search).get('devInitData') ?? '';

  let mainButtonHandler: (() => void) | null = null;
  let backButtonHandler: (() => void) | null = null;
  let mainButtonEl: HTMLButtonElement | null = null;
  let backButtonEl: HTMLButtonElement | null = null;

  function ensureMainButton(): HTMLButtonElement {
    if (mainButtonEl) return mainButtonEl;
    mainButtonEl = document.createElement('button');
    mainButtonEl.id = 'dev-tg-main-button';
    mainButtonEl.style.cssText =
      'position:fixed;left:16px;right:16px;bottom:16px;height:48px;border:none;border-radius:12px;' +
      'background:#0d3a63;color:#fff;font-weight:700;font-size:15px;z-index:1000;display:none;cursor:pointer;';
    mainButtonEl.onclick = () => mainButtonHandler?.();
    document.body.appendChild(mainButtonEl);
    return mainButtonEl;
  }

  function ensureBackButton(): HTMLButtonElement {
    if (backButtonEl) return backButtonEl;
    backButtonEl = document.createElement('button');
    backButtonEl.id = 'dev-tg-back-button';
    backButtonEl.textContent = '←';
    backButtonEl.style.cssText =
      'position:fixed;left:12px;top:12px;width:36px;height:36px;border:none;border-radius:50%;' +
      'background:rgba(0,0,0,0.08);font-size:18px;z-index:1000;display:none;cursor:pointer;';
    backButtonEl.onclick = () => backButtonHandler?.();
    document.body.appendChild(backButtonEl);
    return backButtonEl;
  }

  function parseUser() {
    try {
      const userJson = new URLSearchParams(initData).get('user');
      return userJson ? JSON.parse(userJson) : { id: 0, first_name: 'Dev' };
    } catch {
      return { id: 0, first_name: 'Dev' };
    }
  }

  const stub: TelegramWebApp = {
    initData,
    initDataUnsafe: { user: parseUser() },
    themeParams: {},
    colorScheme: 'light',
    isExpanded: true,
    ready() {},
    expand() {},
    close() {
      // eslint-disable-next-line no-alert
      alert('WebApp.close() — v reálném Telegramu by se teď aplikace zavřela.');
    },
    MainButton: {
      text: '',
      show() {
        ensureMainButton().style.display = 'block';
      },
      hide() {
        if (mainButtonEl) mainButtonEl.style.display = 'none';
      },
      enable() {
        ensureMainButton().disabled = false;
      },
      disable() {
        ensureMainButton().disabled = true;
      },
      setText(text: string) {
        ensureMainButton().textContent = text;
      },
      onClick(cb) {
        mainButtonHandler = cb;
      },
      offClick() {
        mainButtonHandler = null;
      },
      showProgress() {},
      hideProgress() {},
    },
    BackButton: {
      show() {
        ensureBackButton().style.display = 'flex';
      },
      hide() {
        if (backButtonEl) backButtonEl.style.display = 'none';
      },
      onClick(cb) {
        backButtonHandler = cb;
      },
      offClick() {
        backButtonHandler = null;
      },
    },
    HapticFeedback: {
      impactOccurred() {},
      notificationOccurred() {},
    },
  };

  window.Telegram = { WebApp: stub };
}
